version: '3.4'

services:
  apiserver:
    image: ${DOCKER_REGISTRY-}apiserver
    build:
      context: ../ApiServer/
      dockerfile: Dockerfile

  webscraper:
    image: ${DOCKER_REGISTRY-}webscraper
    build:
      context: ../WebScraper
      dockerfile: Dockerfile
    depends_on:
      - apiserver

  

